# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
    -   id: autoflake
        args:
        - --in-place
        - --remove-unused-variables
        - --remove-all-unused-imports

-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
        args:
        - --line-length=120


-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-docstring-first
    -   id: detect-private-key

-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        args:
        - --max-line-length=120
        - --max-doc-length=120
        - --ignore=E203,W503,E712,E731
        # E712 comparision funktioniert nicht gut mit inplace operationen von pandas deshalb deaktiviert.
        # E731 Lambda Avoidance can be avoided

-   repo: https://github.com/PyCQA/pylint
    rev: v2.13.4
    hooks:
    -   id: pylint
        args:
        - --disable=unused-argument
        - --max-line-length=120

-   repo: https://github.com/PyCQA/pydocstyle
    rev: 6.1.1
    hooks:
    -   id: pydocstyle


-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.942
    hooks:
    -   id: mypy
        additional_dependencies:
        - types-requests
        args:
        - --ignore-missing-imports
